version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:latest
    container_name: my_dbt
    depends_on:
      - postgres
    volumes:
      - .:/usr/app
      - ./profiles.yml:/root/.dbt/profiles.yml
    command: ["run"]

