config:
  send_anonymous_usage_stats: False

chinese_fine_art:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: my_user
      password: my_password
      port: 5432
      dbname: my_database
      schema: public