config:
  send_anonymous_usage_stats: False

art_catalog:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: my_user
      password: my_password
      port: 5432
      dbname: my_database
      schema: public